@startuml
skinparam classAttributeIconSize 0

class Account{

}
class ATM {

}
class BalanceInquiry{

}
class BankDatabase{

}
class CashDispenser{

}

class Deposit{

}

class DepositSlot{

}

class Keypad{

}
class Screen {

}

class Withdrawal{

}



@enduml