@startuml
skinparam classAttributeIconSize 0

class Account{

}

class BankDatabase{

}

class Screen {
}

class Keypad{

}

class CashDispenser{

}

class Withdrawal{
}

class DepositSlot{

}

class ATM {
}



ATM "1" *-- "1" DepositSlot
ATM "1" *-- "1" Keypad
ATM "1" *-- "1" CashDispenser
ATM "1" *-- "1" Screen
ATM "1" -- "0..1" Withdrawal : Executa >
ATM "1" -- "1" BankDatabase : Autentica o usuário contra >
BankDatabase "1" *-- "0..*" Account : Contem > 
Withdrawal "0..1" -- BankDatabase: Acessa/Modifica o saldo de uma conta >
Withdrawal "0..1" -- "1" Screen
Withdrawal "0..1" -- "1" CashDispenser
Withdrawal "0..1" -- "1" Keypad



@enduml