@startuml
skinparam classAttributeIconSize 0

class Screen {

}


class ATM {
    -numero-serie
    -interno()
    +ligar()
    +desligar()
    +realizarSaque()
    +realizarDepoisito()

}

class Keypad{

}
class DepositSlot{

}
class CashDispenser{

}

ATM "1" *-- "1" DepositSlot
ATM "1" *-- "1" Keypad
ATM "1" *-- "1" CashDispenser
ATM "1" *-- "1" Screen


@enduml