
@startuml
state "obter saldo disponível da conta de usuário a partir do banco de dados" as state1
state "obter o saldo total da conta do usuário a partir do banco de dados" as state2
state "exibir saldos na tela" as state3

[*] -down-> state1
state1 -down-> state2  
state2 -down-> state3
state3 -down-> [*]

@enduml