@startuml
left to right direction
actor "Usuário" as fc
rectangle ATM {
  usecase "Balance Inquiry" as UC1
  usecase "Withdrawal" as UC2
  usecase "Deposit" as UC3
}
fc --> UC1
fc --> UC2
fc --> UC3
@enduml