-- MySQL Script generated by MySQL Workbench
-- Fri 25 Feb 2022 05:53:25 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dwsucos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dwsucos` ;

-- -----------------------------------------------------
-- Schema dwsucos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dwsucos` ;
-- -----------------------------------------------------
-- Schema dmPresidencia
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dmPresidencia` ;

-- -----------------------------------------------------
-- Schema dmPresidencia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dmPresidencia` ;
USE `dwsucos` ;

-- -----------------------------------------------------
-- Table `Dim_Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dim_Categoria` ;

CREATE TABLE IF NOT EXISTS `Dim_Categoria` (
  `cod_categoria` NVARCHAR(50) NOT NULL,
  `desc_categoria` NVARCHAR(250) NOT NULL,
  PRIMARY KEY (`cod_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dim_Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dim_Cliente` ;

CREATE TABLE IF NOT EXISTS `Dim_Cliente` (
  `cod_cliente` NVARCHAR(50) NOT NULL,
  `desc_cliente` NVARCHAR(250) NOT NULL,
  `cod_cidade` NVARCHAR(50) NOT NULL,
  `desc_cidade` NVARCHAR(250) NOT NULL,
  `cod_estato` NVARCHAR(50) NOT NULL,
  `desc_estado` NVARCHAR(250) NOT NULL,
  `cod_regiao` NVARCHAR(50) NOT NULL,
  `desc_regiao` NVARCHAR(250) NOT NULL,
  `cod_segmento` NVARCHAR(50) NOT NULL,
  `desc_segmento` NVARCHAR(250) NOT NULL,
  PRIMARY KEY (`cod_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dim_Fabrica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dim_Fabrica` ;

CREATE TABLE IF NOT EXISTS `Dim_Fabrica` (
  `cod_fabrica` NVARCHAR(50) NOT NULL,
  `Desc_Fabrica` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`cod_fabrica`))
ENGINE = InnoDB
COMMENT = 'Tabela de dimensão fábrica'
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `Dim_Marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dim_Marca` ;

CREATE TABLE IF NOT EXISTS `Dim_Marca` (
  `cod_marca` NVARCHAR(50) NOT NULL,
  `desc_marca` NVARCHAR(250) NULL DEFAULT NULL,
  `cod_categoria` NVARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_marca`),
  CONSTRAINT `fk_dim_marca_dim_categoria1`
    FOREIGN KEY (`cod_categoria`)
    REFERENCES `Dim_Categoria` (`cod_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dim_Organizacional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dim_Organizacional` ;

CREATE TABLE IF NOT EXISTS `Dim_Organizacional` (
  `cod_organizacional` NVARCHAR(50) NOT NULL,
  `desc_organizacional` NVARCHAR(250) NULL,
  `cod_oraganizacional_pai` NVARCHAR(50) NULL,
  `esquerda` INT NULL,
  `direita` INT NULL,
  `nivel` INT NULL,
  PRIMARY KEY (`cod_organizacional`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dim_Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dim_Produto` ;

CREATE TABLE IF NOT EXISTS `Dim_Produto` (
  `cod_produto` NVARCHAR(50) NOT NULL,
  `desc_produto` NVARCHAR(250) NULL DEFAULT NULL,
  `cod_marca` NVARCHAR(50) NULL DEFAULT NULL,
  `atr_tamanho` NVARCHAR(250) NULL DEFAULT NULL,
  `atr_sabor` NVARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_produto`),
  CONSTRAINT `fk_dim_produto_dim_marca`
    FOREIGN KEY (`cod_marca`)
    REFERENCES `Dim_Marca` (`cod_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dim_Tempo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dim_Tempo` ;

CREATE TABLE IF NOT EXISTS `Dim_Tempo` (
  `cod_tempo` NVARCHAR(50) NOT NULL,
  `dia` DATE NOT NULL,
  `numero_dia_semana` NVARCHAR(50) NOT NULL,
  `numero_mes` NVARCHAR(50) NOT NULL,
  `numero_ano` NVARCHAR(50) NOT NULL,
  `desc_mes` NVARCHAR(250) NOT NULL,
  `numero_trimestre` NVARCHAR(50) NOT NULL,
  `nome_trimestre` NVARCHAR(250) NOT NULL,
  `numero_semestre` NVARCHAR(50) NOT NULL,
  `nome_semestre` NVARCHAR(250) NOT NULL,
  PRIMARY KEY (`cod_tempo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fato001`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fato001` ;

CREATE TABLE IF NOT EXISTS `Fato001` (
  `cod_fabrica` NVARCHAR(50) NOT NULL,
  `cod_tempo` NVARCHAR(50) NOT NULL,
  `cod_cliente` NVARCHAR(50) NOT NULL,
  `cod_organizacional` NVARCHAR(50) NOT NULL,
  `cod_produto` NVARCHAR(50) NOT NULL,
  `faturamento` DOUBLE NULL,
  `unidade_vendida` DOUBLE NULL,
  `quantidade_vendida` DOUBLE NULL,
  `imposto` DOUBLE NULL,
  `custo_variavel` DOUBLE NULL,
  PRIMARY KEY (`cod_fabrica`, `cod_tempo`, `cod_cliente`, `cod_organizacional`, `cod_produto`),
  CONSTRAINT `fk_Fato001_Dim_Fabrica1`
    FOREIGN KEY (`cod_fabrica`)
    REFERENCES `Dim_Fabrica` (`cod_fabrica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato001_Dim_Tempo1`
    FOREIGN KEY (`cod_tempo`)
    REFERENCES `Dim_Tempo` (`cod_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato001_Dim_Cliente1`
    FOREIGN KEY (`cod_cliente`)
    REFERENCES `Dim_Cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato001_Dim_Organizacional1`
    FOREIGN KEY (`cod_organizacional`)
    REFERENCES `Dim_Organizacional` (`cod_organizacional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato001_Dim_Produto1`
    FOREIGN KEY (`cod_produto`)
    REFERENCES `Dim_Produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fato002`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fato002` ;

CREATE TABLE IF NOT EXISTS `Fato002` (
  `Cod_Fabrica` NVARCHAR(50) NOT NULL,
  `cod_tempo` NVARCHAR(50) NOT NULL,
  `cod_cliente` NVARCHAR(50) NOT NULL,
  `cod_produto` NVARCHAR(50) NOT NULL,
  `custo_frete` VARCHAR(45) NULL,
  PRIMARY KEY (`Cod_Fabrica`, `cod_tempo`, `cod_cliente`, `cod_produto`),
  CONSTRAINT `fk_Fato002_Dim_Fabrica1`
    FOREIGN KEY (`Cod_Fabrica`)
    REFERENCES `Dim_Fabrica` (`cod_fabrica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato002_Dim_Tempo1`
    FOREIGN KEY (`cod_tempo`)
    REFERENCES `Dim_Tempo` (`cod_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato002_Dim_Cliente1`
    FOREIGN KEY (`cod_cliente`)
    REFERENCES `Dim_Cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato002_Dim_Produto1`
    FOREIGN KEY (`cod_produto`)
    REFERENCES `Dim_Produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fato003`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fato003` ;

CREATE TABLE IF NOT EXISTS `Fato003` (
  `cod_fabrica` NVARCHAR(50) NOT NULL,
  `cod_tempo` NVARCHAR(50) NOT NULL,
  `custo_fixo` DOUBLE NULL,
  PRIMARY KEY (`cod_fabrica`, `cod_tempo`),
  CONSTRAINT `fk_Fato003_Dim_Fabrica1`
    FOREIGN KEY (`cod_fabrica`)
    REFERENCES `Dim_Fabrica` (`cod_fabrica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato003_Dim_Tempo1`
    FOREIGN KEY (`cod_tempo`)
    REFERENCES `Dim_Tempo` (`cod_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fato004`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fato004` ;

CREATE TABLE IF NOT EXISTS `Fato004` (
  `cod_produto` NVARCHAR(50) NOT NULL,
  `cod_organizacional` NVARCHAR(50) NOT NULL,
  `cod_cliente` NVARCHAR(50) NOT NULL,
  `cod_tempo` NVARCHAR(50) NOT NULL,
  `metas_faturamento` DOUBLE NULL,
  PRIMARY KEY (`cod_produto`, `cod_organizacional`, `cod_cliente`, `cod_tempo`),
  CONSTRAINT `fk_Fato004_Dim_Produto1`
    FOREIGN KEY (`cod_produto`)
    REFERENCES `Dim_Produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato004_Dim_Cliente1`
    FOREIGN KEY (`cod_cliente`)
    REFERENCES `Dim_Cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato004_Dim_Tempo1`
    FOREIGN KEY (`cod_tempo`)
    REFERENCES `Dim_Tempo` (`cod_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato004_Dim_Organizacional1`
    FOREIGN KEY (`cod_organizacional`)
    REFERENCES `Dim_Organizacional` (`cod_organizacional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fato005`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fato005` ;

CREATE TABLE IF NOT EXISTS `Fato005` (
  `cod_produto` NVARCHAR(50) NOT NULL,
  `cod_fabrica` NVARCHAR(50) NOT NULL,
  `cod_tempo` NVARCHAR(50) NOT NULL,
  `meta_custo` DOUBLE NULL,
  PRIMARY KEY (`cod_produto`, `cod_fabrica`, `cod_tempo`),
  CONSTRAINT `fk_Fato005_Dim_Produto1`
    FOREIGN KEY (`cod_produto`)
    REFERENCES `Dim_Produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato005_Dim_Fabrica1`
    FOREIGN KEY (`cod_fabrica`)
    REFERENCES `Dim_Fabrica` (`cod_fabrica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato005_Dim_Tempo1`
    FOREIGN KEY (`cod_tempo`)
    REFERENCES `Dim_Tempo` (`cod_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `dmPresidencia` ;

-- -----------------------------------------------------
-- Table `Fabrica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fabrica` ;

CREATE TABLE IF NOT EXISTS `Fabrica` (
  `cod_fabrica` NVARCHAR(50) NOT NULL,
  `Desc_Fabrica` VARCHAR(250) NOT NULL,
  `id_fabrica` INT NULL,
  PRIMARY KEY (`cod_fabrica`))
ENGINE = InnoDB
COMMENT = 'Tabela de dimensão fábrica'
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `Fato_presidencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fato_presidencia` ;

CREATE TABLE IF NOT EXISTS `Fato_presidencia` (
  `cod_fabrica` NVARCHAR(50) NOT NULL,
  PRIMARY KEY (`cod_fabrica`),
  CONSTRAINT `fk_dmPresidencia_Fabrica`
    FOREIGN KEY (`cod_fabrica`)
    REFERENCES `Fabrica` (`cod_fabrica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
