-- MySQL Script generated by MySQL Workbench
-- Mon 21 Feb 2022 11:52:35 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dwsucos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dwsucos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dwsucos` ;
USE `dwsucos` ;

-- -----------------------------------------------------
-- Table `dwsucos`.`Dim_Fabrica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsucos`.`Dim_Fabrica` (
  `Cod_Fabrica` NVARCHAR(50) NOT NULL,
  `Desc_Fabrica` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`Cod_Fabrica`))
ENGINE = InnoDB
COMMENT = 'Tabela de dimensão fábrica'
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `dwsucos`.`Dim_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsucos`.`Dim_Cliente` (
  `cod_cliente` NVARCHAR(50) NOT NULL,
  `desc_cliente` NVARCHAR(250) NOT NULL,
  `cod_cidade` NVARCHAR(50) NOT NULL,
  `desc_cidade` NVARCHAR(250) NOT NULL,
  `cod_estato` NVARCHAR(50) NOT NULL,
  `desc_estado` NVARCHAR(250) NOT NULL,
  `cod_regiao` NVARCHAR(50) NOT NULL,
  `desc_regiao` NVARCHAR(250) NOT NULL,
  `cod_segmento` NVARCHAR(50) NOT NULL,
  `desc_segmento` NVARCHAR(250) NOT NULL,
  PRIMARY KEY (`cod_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwsucos`.`Dim_Tempo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsucos`.`Dim_Tempo` (
  `cod_tempo` NVARCHAR(50) NOT NULL,
  `dia` DATE NOT NULL,
  `numero_dia_semana` NVARCHAR(50) NOT NULL,
  `numero_mes` NVARCHAR(50) NOT NULL,
  `numero_ano` NVARCHAR(50) NOT NULL,
  `desc_mes` NVARCHAR(250) NOT NULL,
  `numero_trimestre` NVARCHAR(50) NOT NULL,
  `nome_trimestre` NVARCHAR(250) NOT NULL,
  `numero_semestre` NVARCHAR(50) NOT NULL,
  `nome_semestre` NVARCHAR(250) NOT NULL,
  PRIMARY KEY (`cod_tempo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwsucos`.`Dim_Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsucos`.`Dim_Categoria` (
  `cod_categoria` NVARCHAR(50) NOT NULL,
  `desc_categoria` NVARCHAR(250) NOT NULL,
  PRIMARY KEY (`cod_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwsucos`.`Dim_Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsucos`.`Dim_Marca` (
  `cod_marca` NVARCHAR(50) NOT NULL,
  `desc_marca` NVARCHAR(250) NULL,
  `cod_categoria` NVARCHAR(50) NULL,
  PRIMARY KEY (`cod_marca`),
  INDEX `fk_dim_marca_dim_categoria1_idx` (`cod_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_dim_marca_dim_categoria1`
    FOREIGN KEY (`cod_categoria`)
    REFERENCES `dwsucos`.`Dim_Categoria` (`cod_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwsucos`.`Dim_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsucos`.`Dim_Produto` (
  `cod_produto` NVARCHAR(50) NOT NULL,
  `desc_produto` NVARCHAR(250) NULL,
  `cod_marca` NVARCHAR(50) NULL,
  `atr_tamanho` NVARCHAR(250) NULL,
  `atr_sabor` NVARCHAR(250) NULL,
  PRIMARY KEY (`cod_produto`),
  INDEX `fk_dim_produto_dim_marca_idx` (`cod_marca` ASC) VISIBLE,
  CONSTRAINT `fk_dim_produto_dim_marca`
    FOREIGN KEY (`cod_marca`)
    REFERENCES `dwsucos`.`Dim_Marca` (`cod_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwsucos`.`Dim_Organizacional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsucos`.`Dim_Organizacional` (
  `cod_organizacional` NVARCHAR(50) NOT NULL,
  `desc_organizacional` NVARCHAR(250) NULL,
  `cod_oraganizacional_pai` NVARCHAR(50) NULL,
  `esquerda` INT NULL,
  `direita` INT NULL,
  `nivel` INT NULL,
  PRIMARY KEY (`cod_organizacional`),
  INDEX `fk_dim_organizacional_dim_organizacional1_idx` (`cod_oraganizacional_pai` ASC) VISIBLE,
  CONSTRAINT `fk_dim_organizacional_dim_organizacional1`
    FOREIGN KEY (`cod_oraganizacional_pai`)
    REFERENCES `dwsucos`.`Dim_Organizacional` (`cod_organizacional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
