-- MySQL Script generated by MySQL Workbench
-- Fri 25 Feb 2022 10:25:33 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dwsucos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dwsucos` ;

-- -----------------------------------------------------
-- Schema dwsucos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dwsucos` ;
-- -----------------------------------------------------
-- Schema dmPresidencia
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dmPresidencia` ;

-- -----------------------------------------------------
-- Schema dmPresidencia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dmPresidencia` ;
USE `dwsucos` ;

-- -----------------------------------------------------
-- Table `dwsucos`.`Dim_Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsucos`.`Dim_Categoria` (
  `cod_categoria` NVARCHAR(50) NOT NULL,
  `desc_categoria` NVARCHAR(250) NOT NULL,
  PRIMARY KEY (`cod_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwsucos`.`Dim_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsucos`.`Dim_Cliente` (
  `cod_cliente` NVARCHAR(50) NOT NULL,
  `desc_cliente` NVARCHAR(250) NOT NULL,
  `cod_cidade` NVARCHAR(50) NOT NULL,
  `desc_cidade` NVARCHAR(250) NOT NULL,
  `cod_estato` NVARCHAR(50) NOT NULL,
  `desc_estado` NVARCHAR(250) NOT NULL,
  `cod_regiao` NVARCHAR(50) NOT NULL,
  `desc_regiao` NVARCHAR(250) NOT NULL,
  `cod_segmento` NVARCHAR(50) NOT NULL,
  `desc_segmento` NVARCHAR(250) NOT NULL,
  PRIMARY KEY (`cod_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwsucos`.`Dim_Fabrica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsucos`.`Dim_Fabrica` (
  `cod_fabrica` NVARCHAR(50) NOT NULL,
  `Desc_Fabrica` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`cod_fabrica`))
ENGINE = InnoDB
COMMENT = 'Tabela de dimensão fábrica'
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `dwsucos`.`Dim_Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsucos`.`Dim_Marca` (
  `cod_marca` NVARCHAR(50) NOT NULL,
  `desc_marca` NVARCHAR(250) NULL DEFAULT NULL,
  `cod_categoria` NVARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_marca`),
  INDEX `fk_dim_marca_dim_categoria1` (`cod_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_dim_marca_dim_categoria1`
    FOREIGN KEY (`cod_categoria`)
    REFERENCES `dwsucos`.`Dim_Categoria` (`cod_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwsucos`.`Dim_Organizacional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsucos`.`Dim_Organizacional` (
  `cod_organizacional` NVARCHAR(50) NOT NULL,
  `desc_organizacional` NVARCHAR(250) NULL DEFAULT NULL,
  `cod_oraganizacional_pai` NVARCHAR(50) NULL DEFAULT NULL,
  `esquerda` INT NULL DEFAULT NULL,
  `direita` INT NULL DEFAULT NULL,
  `nivel` INT NULL DEFAULT NULL,
  PRIMARY KEY (`cod_organizacional`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwsucos`.`Dim_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsucos`.`Dim_Produto` (
  `cod_produto` NVARCHAR(50) NOT NULL,
  `desc_produto` NVARCHAR(250) NULL DEFAULT NULL,
  `cod_marca` NVARCHAR(50) NULL DEFAULT NULL,
  `atr_tamanho` NVARCHAR(250) NULL DEFAULT NULL,
  `atr_sabor` NVARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_produto`),
  INDEX `fk_dim_produto_dim_marca` (`cod_marca` ASC) VISIBLE,
  CONSTRAINT `fk_dim_produto_dim_marca`
    FOREIGN KEY (`cod_marca`)
    REFERENCES `dwsucos`.`Dim_Marca` (`cod_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwsucos`.`Dim_Tempo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsucos`.`Dim_Tempo` (
  `cod_tempo` NVARCHAR(50) NOT NULL,
  `dia` DATE NOT NULL,
  `numero_dia_semana` NVARCHAR(50) NOT NULL,
  `numero_mes` NVARCHAR(50) NOT NULL,
  `numero_ano` NVARCHAR(50) NOT NULL,
  `desc_mes` NVARCHAR(250) NOT NULL,
  `numero_trimestre` NVARCHAR(50) NOT NULL,
  `nome_trimestre` NVARCHAR(250) NOT NULL,
  `numero_semestre` NVARCHAR(50) NOT NULL,
  `nome_semestre` NVARCHAR(250) NOT NULL,
  PRIMARY KEY (`cod_tempo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwsucos`.`Fato001`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsucos`.`Fato001` (
  `cod_fabrica` NVARCHAR(50) NOT NULL,
  `cod_tempo` NVARCHAR(50) NOT NULL,
  `cod_cliente` NVARCHAR(50) NOT NULL,
  `cod_organizacional` NVARCHAR(50) NOT NULL,
  `cod_produto` NVARCHAR(50) NOT NULL,
  `faturamento` DOUBLE NULL DEFAULT NULL,
  `unidade_vendida` DOUBLE NULL DEFAULT NULL,
  `quantidade_vendida` DOUBLE NULL DEFAULT NULL,
  `imposto` DOUBLE NULL DEFAULT NULL,
  `custo_variavel` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`cod_fabrica`, `cod_tempo`, `cod_cliente`, `cod_organizacional`, `cod_produto`),
  INDEX `fk_Fato001_Dim_Tempo1` (`cod_tempo` ASC) VISIBLE,
  INDEX `fk_Fato001_Dim_Cliente1` (`cod_cliente` ASC) VISIBLE,
  INDEX `fk_Fato001_Dim_Organizacional1` (`cod_organizacional` ASC) VISIBLE,
  INDEX `fk_Fato001_Dim_Produto1` (`cod_produto` ASC) VISIBLE,
  CONSTRAINT `fk_Fato001_Dim_Fabrica1`
    FOREIGN KEY (`cod_fabrica`)
    REFERENCES `dwsucos`.`Dim_Fabrica` (`cod_fabrica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato001_Dim_Tempo1`
    FOREIGN KEY (`cod_tempo`)
    REFERENCES `dwsucos`.`Dim_Tempo` (`cod_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato001_Dim_Cliente1`
    FOREIGN KEY (`cod_cliente`)
    REFERENCES `dwsucos`.`Dim_Cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato001_Dim_Organizacional1`
    FOREIGN KEY (`cod_organizacional`)
    REFERENCES `dwsucos`.`Dim_Organizacional` (`cod_organizacional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato001_Dim_Produto1`
    FOREIGN KEY (`cod_produto`)
    REFERENCES `dwsucos`.`Dim_Produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwsucos`.`Fato002`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsucos`.`Fato002` (
  `Cod_Fabrica` NVARCHAR(50) NOT NULL,
  `cod_tempo` NVARCHAR(50) NOT NULL,
  `cod_cliente` NVARCHAR(50) NOT NULL,
  `cod_produto` NVARCHAR(50) NOT NULL,
  `custo_frete` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_Fabrica`, `cod_tempo`, `cod_cliente`, `cod_produto`),
  INDEX `fk_Fato002_Dim_Tempo1` (`cod_tempo` ASC) VISIBLE,
  INDEX `fk_Fato002_Dim_Cliente1` (`cod_cliente` ASC) VISIBLE,
  INDEX `fk_Fato002_Dim_Produto1` (`cod_produto` ASC) VISIBLE,
  CONSTRAINT `fk_Fato002_Dim_Fabrica1`
    FOREIGN KEY (`Cod_Fabrica`)
    REFERENCES `dwsucos`.`Dim_Fabrica` (`cod_fabrica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato002_Dim_Tempo1`
    FOREIGN KEY (`cod_tempo`)
    REFERENCES `dwsucos`.`Dim_Tempo` (`cod_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato002_Dim_Cliente1`
    FOREIGN KEY (`cod_cliente`)
    REFERENCES `dwsucos`.`Dim_Cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato002_Dim_Produto1`
    FOREIGN KEY (`cod_produto`)
    REFERENCES `dwsucos`.`Dim_Produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwsucos`.`Fato003`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsucos`.`Fato003` (
  `cod_fabrica` NVARCHAR(50) NOT NULL,
  `cod_tempo` NVARCHAR(50) NOT NULL,
  `custo_fixo` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`cod_fabrica`, `cod_tempo`),
  INDEX `fk_Fato003_Dim_Tempo1` (`cod_tempo` ASC) VISIBLE,
  CONSTRAINT `fk_Fato003_Dim_Fabrica1`
    FOREIGN KEY (`cod_fabrica`)
    REFERENCES `dwsucos`.`Dim_Fabrica` (`cod_fabrica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato003_Dim_Tempo1`
    FOREIGN KEY (`cod_tempo`)
    REFERENCES `dwsucos`.`Dim_Tempo` (`cod_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwsucos`.`Fato004`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsucos`.`Fato004` (
  `cod_produto` NVARCHAR(50) NOT NULL,
  `cod_organizacional` NVARCHAR(50) NOT NULL,
  `cod_cliente` NVARCHAR(50) NOT NULL,
  `cod_tempo` NVARCHAR(50) NOT NULL,
  `metas_faturamento` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`cod_produto`, `cod_organizacional`, `cod_cliente`, `cod_tempo`),
  INDEX `fk_Fato004_Dim_Cliente1` (`cod_cliente` ASC) VISIBLE,
  INDEX `fk_Fato004_Dim_Tempo1` (`cod_tempo` ASC) VISIBLE,
  INDEX `fk_Fato004_Dim_Organizacional1` (`cod_organizacional` ASC) VISIBLE,
  CONSTRAINT `fk_Fato004_Dim_Produto1`
    FOREIGN KEY (`cod_produto`)
    REFERENCES `dwsucos`.`Dim_Produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato004_Dim_Cliente1`
    FOREIGN KEY (`cod_cliente`)
    REFERENCES `dwsucos`.`Dim_Cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato004_Dim_Tempo1`
    FOREIGN KEY (`cod_tempo`)
    REFERENCES `dwsucos`.`Dim_Tempo` (`cod_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato004_Dim_Organizacional1`
    FOREIGN KEY (`cod_organizacional`)
    REFERENCES `dwsucos`.`Dim_Organizacional` (`cod_organizacional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwsucos`.`Fato005`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsucos`.`Fato005` (
  `cod_produto` NVARCHAR(50) NOT NULL,
  `cod_fabrica` NVARCHAR(50) NOT NULL,
  `cod_tempo` NVARCHAR(50) NOT NULL,
  `meta_custo` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`cod_produto`, `cod_fabrica`, `cod_tempo`),
  INDEX `fk_Fato005_Dim_Fabrica1` (`cod_fabrica` ASC) VISIBLE,
  INDEX `fk_Fato005_Dim_Tempo1` (`cod_tempo` ASC) VISIBLE,
  CONSTRAINT `fk_Fato005_Dim_Produto1`
    FOREIGN KEY (`cod_produto`)
    REFERENCES `dwsucos`.`Dim_Produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato005_Dim_Fabrica1`
    FOREIGN KEY (`cod_fabrica`)
    REFERENCES `dwsucos`.`Dim_Fabrica` (`cod_fabrica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato005_Dim_Tempo1`
    FOREIGN KEY (`cod_tempo`)
    REFERENCES `dwsucos`.`Dim_Tempo` (`cod_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `dmPresidencia` ;

-- -----------------------------------------------------
-- Table `dmPresidencia`.`Dim_Fabrica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dmPresidencia`.`Dim_Fabrica` (
  `id_fabrica` INT NOT NULL,
  `cod_fabrica` NVARCHAR(50) NOT NULL,
  `Desc_Fabrica` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_fabrica`))
ENGINE = InnoDB
COMMENT = 'Tabela de dimensão fábrica'
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `dmPresidencia`.`Dim_Tempo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dmPresidencia`.`Dim_Tempo` (
  `id_tempo` INT NOT NULL,
  `cod_tempo` NVARCHAR(50) NOT NULL,
  `dia` DATE NOT NULL,
  `numero_dia_semana` NVARCHAR(50) NOT NULL,
  `numero_mes` NVARCHAR(50) NOT NULL,
--  `ID_Tempo` NVARCHAR(50) NOT NULL,
  `desc_mes` NVARCHAR(250) NOT NULL,
  `numero_trimestre` NVARCHAR(50) NOT NULL,
  `nome_trimestre` NVARCHAR(250) NOT NULL,
  `numero_semestre` NVARCHAR(50) NOT NULL,
  `nome_semestre` NVARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_tempo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dmPresidencia`.`Dim_Organizacional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dmPresidencia`.`Dim_Organizacional` (
  `id_vendedor` INT NOT NULL,
  `cod_vendedor` NVARCHAR(50) NULL,
  `desc_vendedor` NVARCHAR(250) NULL DEFAULT NULL,
  `cod_gerente` NVARCHAR(50) NULL DEFAULT NULL,
  `desc_gerente` NVARCHAR(250) NULL DEFAULT NULL,
  `cod_diretor` NVARCHAR(50) NULL DEFAULT NULL,
  `desc_diretor` NVARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id_vendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dmPresidencia`.`Dim_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dmPresidencia`.`Dim_Cliente` (
  `id_cliente` INT NOT NULL,
  `cod_cliente` NVARCHAR(50) NOT NULL,
  `desc_cliente` NVARCHAR(250) NOT NULL,
  `cod_cidade` NVARCHAR(50) NOT NULL,
  `desc_cidade` NVARCHAR(250) NOT NULL,
  `cod_estato` NVARCHAR(50) NOT NULL,
  `desc_estado` NVARCHAR(250) NOT NULL,
  `cod_regiao` NVARCHAR(50) NOT NULL,
  `desc_regiao` NVARCHAR(250) NOT NULL,
  `cod_segmento` NVARCHAR(50) NOT NULL,
--  `ID_Cliente` NVARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dmPresidencia`.`Dim_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dmPresidencia`.`Dim_Produto` (
  `id_produto` INT NOT NULL,
  `cod_produto` NVARCHAR(50) NULL,
  `desc_produto` NVARCHAR(250) NULL DEFAULT NULL,
  `atr_tamanho` NVARCHAR(250) NULL DEFAULT NULL,
  `atr_sabor` NVARCHAR(250) NULL DEFAULT NULL,
  `cod_categoria` NVARCHAR(50) NULL,
  `desc_categoria` NVARCHAR(250) NULL,
  `cod_marca` NVARCHAR(50) NULL,
  `desc_marca` NVARCHAR(250) NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dmPresidencia`.`Fato_presidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dmPresidencia`.`Fato_presidencia` (
  `id_fabrica` INT NOT NULL,
  `id_tempo` INT NOT NULL,
  `id_vendedor` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `faturamento` DOUBLE NULL,
  `unidade_vendida` DOUBLE NULL,
  `quantidade_vendida` DOUBLE NULL,
  `imposto` DOUBLE NULL COMMENT '	',
  `custo_variavel` DOUBLE NULL,
  `custo_fixo` DOUBLE NULL,
  `mata_de_faturamento` DOUBLE NULL,
  `meta_custo` DOUBLE NULL,
  PRIMARY KEY (`id_fabrica`, `id_tempo`, `id_vendedor`, `id_cliente`, `id_produto`),
  INDEX `fk_Fato_presidencia_Tempo1_idx` (`id_tempo` ASC) VISIBLE,
  INDEX `fk_Fato_presidencia_Vendedor1_idx` (`id_vendedor` ASC) VISIBLE,
  INDEX `fk_Fato_presidencia_Cliente1_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_Fato_presidencia_Produto1_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_Fato_presidencia_Fabrica1`
    FOREIGN KEY (`id_fabrica`)
    REFERENCES `dmPresidencia`.`Dim_Fabrica` (`id_fabrica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato_presidencia_Tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `dmPresidencia`.`Dim_Tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato_presidencia_Vendedor1`
    FOREIGN KEY (`id_vendedor`)
    REFERENCES `dmPresidencia`.`Dim_Organizacional` (`id_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato_presidencia_Cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `dmPresidencia`.`Dim_Cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato_presidencia_Produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `dmPresidencia`.`Dim_Produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

DROP USER 'pentaho'@'localhost';

CREATE USER 'pentaho'@'localhost'
  IDENTIFIED BY 'pentaho';

GRANT ALL ON dwsucos.* TO 'pentaho'@'localhost';
GRANT ALL ON dmPresidencia.* TO 'pentaho'@'localhost';

FLUSH PRIVILEGES;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
