@startuml
skinparam classAttributeIconSize 0

class Account{
    - accountNumber : Integer
    - pin : Integer
    - avaliableBalance : Double
    - totalBalance : Double

}
class ATM {
    - userAuthenticated : Boolean = false

}
class BalanceInquiry{
    - accountNumber : Integer

}
class BankDatabase{

}
class CashDispenser{
    count : Integer = 500

}

class Deposit{
    - accountNumber : Integer
    - amount : double
}

class DepositSlot{

}

class Keypad{

}
class Screen {

}

class Withdrawal{
    - accountNumber : Integer
    - amount : double
}



@enduml