@startuml
start
repeat
    :exibe o menu de quantias de \nretirada e opção para cancelar;
    :entrada da seleção de menu;
    if () then ([usuário selecionou \numa quantia])
        : configura o atributo //amount//;
        : obtém //availableBalance// da conta\n de usuário a partir do banco de dados;
        if () then ([quantia <= saldo disponível])
            :testa se dinheiro suficiente está\n disponível no dispensador de cédulas;
            if () then ([dinheiro\n disponível\n suficiente])

                :interage com banco de dados para \ndebitar a quantia da conta do usuário;
                :dispensador de cédulas;
                :instrui o usuário a pegar o dinheiro;

            else ([dinheiro\n disponível\n insuficiente])

                :exibe mensagem de erro;

            endif
        else ([quantia > saldo disponível])
            :exibe mensagem de erro; 
        endif
    else ([usuário cancelou \na transação])
        : exibe mensagem de cancelamento;
    endif
repeat while () is ([dinheiro não fornecido e \nusuário não fez \no cancelamento])
-> [dinheiro fornecido ou \nusuário cancelou \na transação];
stop;
@enduml