@startuml
class Triade{
    Triade(Tecla);
    void setT1(Tecla);
    Tecla getT1();
    void setT3(Tecla);
    Tecla getT3();
    void setT5(Tecla);
    Tecla getT5();
    void GerarTriade(Tecla, string);
    void ImprimirEmTela();
    string GerarDescricao();
    Tecla t1;
    Tecla t3;
    Tecla t5;
}


class Tecla {
    Tecla(); // constructor
    Tecla(int, int, int ); // constructor
    void setTecla( int, int, int ); 
    void setOitava(int);
    void setNota(int);
    void setAcidente(int);
    int getOitava();
    int getNota();
    int getAcidente();
    string GerarDescricao();
    void ImprimirEmTela();
    void Aleatorio();
    Tecla qualRelativa(int);
    int oitava;     // 0--8     / oitavas de um pianao
    int nota;       // 1--7     / do,re,mi,fa,sol,la,si,
    int acidente;   // [-1,0,1] / bemol, sem acidente, sustenido
}

Tecla "3" *-- Triade: Contém

@enduml
