@startuml

Nota "2"--"1" Intervalo 
Triade "1" -- "2" Intervalo

class Nota {
    Nota(); 
    Nota(int, int, int ); 
    void setOitava(int);
    void setGrau(int);
    void setAcidente(int);
    int getOitava();
    int getGrau();
    int getAcidente();
    void setNota( int, int, int ); 
    void Aleatorio();
    Nota qualRelativa(int);
    string GerarDescricao();
    void ImprimirEmTela();
    int oitava;     [1--8]
    int grau;       [1--7]
    int acidente;   [-2,0,2] [bb,b,0,#,*]
}

class Intervalo {
    Intervalo();
    Intervalo(Nota);
    Intervalo(Nota,Nota);
    void setN1(Nota);
    Nota getN1();
    void setN2(Nota);
    Nota getN2();
    void setQtdNotasNaturais(int);
    int  getQtdNotasNaturais();
    void setQtdSemiTons(int);
    int  GetQtdSemiTons();
    void setQualidade(char);
    char getQualidade();
    void DeterminarSegundaNota(string); 
    void DeterminarIntervalo(Nota);    
    string GerarDescricao();
    void ImprimirEmTela();
    Nota n1;
    Nota n2;
    int qtdNotasNaturais; [2-7]
    int qtdSemiTons; [2-12]
    char qualidade; ['m','M','J'];
}

class Triade{
    Triade(Tecla);
    void setT1(Tecla);
    Tecla getT1();
    void setT3(Tecla);
    Tecla getT3();
    void setT5(Tecla);
    Tecla getT5();
    void GerarTriade(Tecla, string);
    void ImprimirEmTela();
    string GerarDescricao();
    Tecla t1;
    Tecla t3;
    Tecla t5;
    int tipoTriade ['M','m','A','d']
}

@enduml
