@startuml
left to right direction
skinparam actorStyle awesome
rectangle "Gerador Exercicio" {
    Package "Intervalo"{
      "Uma nota e um intervalo simples. \n Qual outra nota?" as (Use01)
      "Duas Notas, \n Qual intervalo?" as (Use02)
    }
    Package "Tríade"{
     "Uma fundamental e uma triade (M,m,A,d).\n Qual 3º e 5º ?" as (Use03)
     "Fundamental, 3º e 5º. \n Qual a triade (M,m,A,d)?" as (Use04)
    }
}
:Usuário: --> (Use01)
:Usuário: --> (Use02)
:Usuário: --> (Use03)
:Usuário: --> (Use04)
@enduml
