@startuml
class GradeBook {
  <<constructor>> + GradeBook (name:String)
  - courseName : String
  - instrutor : String
  + setCourseName(name:String)
  + getCourseName(): String
  + setInstrutor(name:String)
  + getInstrutor(): String
  + displayMessage()
}

class Invoice{
  <<constructor>> +Invoice (id : String, descricao : String, quantidade : int, preco-por-item : int)
  - id : String
  - descricao : String
  - quantidade : int
  - preco-por-item : int
  + setId(id:string)
  + getId():string 
  + setDescricao(id:string)
  + getDescricao():string 
  + setQuantidade(id:int)
  + getQuantidade():int
  + setPrecoPorItem(id:int)
  + getPrecoPorItem():int
  + getInvoiceAmmount():int
}

class Employee {
  - nome : string
  - sobreNome : string
  - salarioMensal: int
  <<constructor>> +Employee (nome : String, sobrenome : String, salarioMensal : int)
  + setNome(string nome):void
  + getNome():string
  + setSobreNome(string nome):void
  + getSobreNome():string
  + setSalarioMensal(int salario):void
  + getSalarioMensal():int
  
}
@enduml